@startuml
node "<<device>> Smartphone" {
    node AOSP {
        node "Linux Kernel" {
            [toybox] as toybox_c
            [ping] as ping_c
            node "Zygote" as zygote_n {
                [system_server] as system_server_c
                [Activity Manager] as activity_manager_c
                node "Android Runtime" as art_n1 {
                    [reddit] as reddit_c
                    [OkHttp] as http_lib1
                }
                node "Android Runtime" as art_n2 {
                    [chrome] as chrome_c
                    [OkHttp] as http_lib2
                }
                node "Android Runtime" as art_n3 {
                    [youtube] as youtube_c
                    [OkHttp] as http_lib3
                }

            }

            [lo]
            [wlan]

            [syscalls]
        }
    }
}

activity_manager_c -(0)- system_server_c : "Unix socket\n/dev/socket/zygote"

toybox_c -(0)- syscalls
ping_c -(0)- syscalls
reddit_c -(0)- http_lib1
chrome_c -(0)- http_lib2
youtube_c -(0)- http_lib3

http_lib1 -(0)- syscalls : JNI
http_lib2 -(0)- syscalls : JNI
http_lib3 -(0)- syscalls : JNI

syscalls -(0)- lo
syscalls -(0)- wlan

@enduml
